navsat_transform:
  ros__parameters:
    frequency: 30.0
    delay: 3.0
    magnetic_declination_radians: 0.0
    yaw_offset: 1.5707963 # check this pi/2
    zero_altitude: true
    broadcast_utm_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: true
    wait_for_datum: false

    # Most IMU sensors that have a absolute orientation use north as 0. navsat_transform uses east as 0 (to follow REP 103). 
    # This means there's a yaw_offset of pi/2 (or 1.5707963). The offset is simply a transform from NWU (North West Up) to ENU.