navsat_transform:
  ros__parameters:
    frequency: 30.0
    delay: 3.0 # wait for data to arrive
    magnetic_declination_radians: 0.0 
    yaw_offset: 0.0
    # 1.57 pi/2 - this makes sure the /gps/filtered goes in the right direction
    # has nothing to do with the /odom_global direction
    zero_altitude: true
    broadcast_cartesian_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: false
    wait_for_datum: false

# Most IMU sensors that have a absolute orientation use north as 0. navsat_transform uses east as 0 (to follow REP 103). 
# This means there's a yaw_offset of pi/2 (or 1.5707963). 
# The offset is simply a transform from NWU (North West Up) to ENU.

# If true, navsat_transform_node will not get its heading from the IMU data, but from the input odometry message
# in our case, the imu data (and the quarterion) are good